apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakusers.pepr.dev
spec:
  group: pepr.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                realm:
                  type: string
                keycloakBaseUrl:
                  type: string
                domain:
                  type: string
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    email:
                      type: string
                    enabled:
                      type: boolean
                    emailVerified:
                      type: boolean
                    credentials:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
                          userLabel:
                            type: string
                          createdDate:
                            type: number
                          credentialData:
                            type: string
                          priority:
                            type: string
                          value:
                            type: string
                          temporary:
                            type: boolean
                          device:
                            type: string
                          hashedSaltedValue:
                            type: string
                          salt:
                            type: string
                          hashIterations:
                            type: integer
                            format: int32
                          counter:
                            type: integer
                            format: int32
                          algorithm:
                            type: string
                          digits:
                            type: integer
                            format: int32
                          period:
                            type: integer
                            format: int32
                          config:
                            type: object
                            additionalProperties: true
                    realmRoles:
                      type: array
                      items:
                        type: string
                    clientRoles:
                      type: object
                      additionalProperties:
                        type: array
                        items:
                          type: string
  scope: Namespaced
  names:
    plural: keycloakusers
    singular: keycloakuser
    kind: KeycloakUser