apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakclients.pepr.dev
spec:
  group: pepr.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                realm:
                  type: string
                keycloakBaseUrl:
                  type: string
                domain:
                  type: string
                client:
                  type: object
                  properties:
                    clientId:
                      type: string
                    name:
                      type: string
                    ### OPTIONAL FIELDS ###
                    access:
                      type: object
                      additionalProperties: true
                    adminUrl:
                      type: string
                    alwaysDisplayInConsole:
                      type: boolean
                    attributes:
                      type: object
                      additionalProperties: true
                    authenticationFlowBindingOverrides:
                      type: object
                      additionalProperties: true
                    authorizationServicesEnabled:
                      type: boolean
                    # todo: need to implement this
                    # authorizationSettings:
                    #   $ref: '#/schemas/ResourceServerRepresentation'
                    baseUrl:
                      type: string
                    bearerOnly:
                      type: boolean
                    clientAuthenticatorType:
                      type: string
                    consentRequired:
                      type: boolean
                    defaultClientScopes:
                      type: array
                      items:
                        type: string
                    description:
                      type: string
                    directAccessGrantsEnabled:
                      type: boolean
                    enabled:
                      type: boolean
                    frontchannelLogout:
                      type: boolean
                    fullScopeAllowed:
                      type: boolean
                    id:
                      type: string
                    implicitFlowEnabled:
                      type: boolean
                    nodeReRegistrationTimeout:
                      type: integer
                      format: int32
                    notBefore:
                      type: integer
                      format: int32
                    oauth2DeviceAuthorizationGrantEnabled:
                      type: boolean
                    optionalClientScopes:
                      type: array
                      items:
                        type: string
                    origin:
                      type: string
                    protocol:
                      type: string
                    # todo: need to implement this
                    # protocolMappers:
                    #   type: array
                    #   items:
                    #     $ref: '#/schemas/ProtocolMapperRepresentation'
                    publicClient:
                      type: boolean
                    redirectUris:
                      type: array
                      items:
                        type: string
                    registeredNodes:
                      type: object
                      additionalProperties: true
                    registrationAccessToken:
                      type: string
                    rootUrl:
                      type: string
                    secret:
                      type: string
                    serviceAccountsEnabled:
                      type: boolean
                    standardFlowEnabled:
                      type: boolean
                    surrogateAuthRequired:
                      type: boolean
                    webOrigins:
                      type: array
                      items:
                        type: string
  scope: Namespaced
  names:
    plural: keycloakclients
    singular: keycloakclient
    kind: KeycloakClient