// This file is auto-generated by kubernetes-fluent-client, do not edit manually

import { GenericKind, RegisterKind } from "kubernetes-fluent-client";

export class KeycloakRole extends GenericKind {
  spec?: Spec;
}

export interface Spec {
  attributes?: { [key: string]: string | string[] | boolean };
  clientRole?: boolean;
  composite?: boolean;
  composites?: { [key: string]: string | string[] | boolean };
  containerId?: string;
  description?: string;
  id?: string;
  name?: string;
  scopeParamRequired?: boolean;
}

RegisterKind(KeycloakRole, {
  group: "pepr.dev",
  version: "v1",
  kind: "KeycloakRole",
});
